baseURL = "https://markw.me"
title = "Mark Whitby"
theme = "m10c"
googleAnalytics = "UA-32768332-1"

[permalinks]
  post = "/:slug"

[params]
  author = "Mark Whitby"
  description = "Azure // Open Source // Code"
  [[params.social]]
    name = "github"
    url = "https://github.com/MarkWme"
  [[params.social]]
    name = "twitter"
    url = "https://twitter.com/MarkWme"
  [[params.social]]
    name = "youtube"
    url = "https://www.youtube.com/c/CloudTechTV"

  # Green theme
  [params.style]
  #  darkestColor = "#315659"
  #  darkColor = "#253031"
  #  primaryColor = "#dad865"
  #  lightColor = "#96a879"
  #  lightestColor = "#fff"

  # [params.style]
  #   darkestColor = "#000000"
  #   darkColor = "#212121"
  #   primaryColor = "#ffffff"
  #   lightColor = "#a2a2a2"
  #   lightestColor = "#d3d3d3"
